# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa87974b6742514c57eed7ee477c831c7ff50fb19c44d408819742b95fdd7122ec05fbfdfe20e4a5e8936f06e6f5a3484f2832baca74a7c8b077afacb206d67d

test:
  secret_key_base: 4f56f792eaef090b4fcbb19b54713b62a87e791138e493f80a16f6af6319f6d8119179c10adfec3246ee4dbcb2e497287ab891a90b60e92269881348b4a856f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
